# -*- coding: utf-8 -*-
"""Teleco Chustomer Churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIzK6ghsArX9h5p39BbGeqw_KxYu5JOE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("telecom_customer_churn.csv")
df.head()
df.columns = df.columns.str.strip()
df.drop(columns=["Churn Category", "Churn Reason",], axis=1, inplace=True) ### Unnecessary columns with NaN values thus removed from the data.
print("\ndata:\n", df.head(3))

print("column info:", df.info())

print("dataset shape:",df.shape)

df.head()
print("total null values:",df.isnull().sum().sum())  ## total NaN values in the data =np.int64(20501)

df["Customer ID"].duplicated().sum() ## no duplicates

"""## NaN removing"""

for column in df.select_dtypes(object).columns:
  df[column]=df[column].fillna(df[column].mode()[0])

df.isnull().sum()

for column in df.select_dtypes("number").columns:
  df[column]=df[column].fillna(df[column].median())

df.isnull().sum().sum()
df.head(2)

print("total null values:",df.isnull().sum().sum())

num_cols = df.select_dtypes(include="number").columns

Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

outlier_counts = {}

for col in num_cols:
    lower = Q1[col] - 1.5 * IQR[col]
    upper = Q3[col] + 1.5 * IQR[col]
    outlier_counts[col] = ((df[col] < lower) | (df[col] > upper)).sum()

print(pd.Series(outlier_counts).sort_values(ascending=False))

col = "Avg Monthly GB Download"

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

outliers.head()

"""Outliers were not removed or clipped because they represent real customer behavior, not data errors.

Many outliers correspond to high-usage or high-value customers, which are important for churn prediction.

Applying log or IQR clipping at the cleaning stage can remove useful business signal.

Different models handle outliers differently, so transformations were deferred to model-specific pipelines.

Keeping raw values ensures fair comparison across multiple models.
"""

# Save cleaned dataset properly as Excel file
df.to_excel("teleco_churn_clean_data.xlsx", index=False)

# Verify file saved successfully
import os
print(os.listdir('/content'))    ### for power bi analysis

print(df["Total Revenue"].describe())
print(df["Monthly Charge"].describe())
print(df["Tenure in Months"].describe())

"""# Churned revenue and monthly charges:"""

total_customers = df["Customer ID"].nunique()

total_stayed = (df["Customer Status"] == "Stayed").sum()
total_joined = (df["Customer Status"] == "Joined").sum()
total_churned = (df["Customer Status"] == "Churned").sum()

print("Total customers:", total_customers)
print("Total customers stayed:", total_stayed)
print("Total customers joined:", total_joined)
print("Total customers churned:", total_churned)

print("Percentage of customers who stayed:",round((total_stayed / total_customers) * 100, 2),"%")

print("Percentage of customers who churned:",round((total_churned / total_customers) * 100, 2),"%")

print("Total revenue:", df["Total Revenue"].sum())
print("Total mean revenue:", df["Total Revenue"].mean())
print("Total churned revenue:",df.loc[df["Customer Status"] == "Churned", "Total Revenue"].sum())


print("Total churned monthly charge:",df.loc[df["Customer Status"] == "Churned", "Monthly Charge"].sum())
print("Total mean churned onthly charge:", df.loc[df["Customer Status"]=="Churned", "Monthly Charge"].mean()) ### 73.34
print("Total mean not churned monthly charge:", df.loc[df["Customer Status"]=="Stayed", "Monthly Charge"].mean())   ###61.73

"""## Month to month contract has highest churn counts"""

print("\n Contrct type churn counts:\n", df["Contract"][df["Customer Status"]=="Churned"].value_counts())

df["Lifetime Revenue"] = df["Monthly Charge"] * df["Tenure in Months"]

print(
    "Total churned lifetime revenue:",
    df.loc[df["Customer Status"] == "Churned", "Lifetime Revenue"].sum()
)

"""## Total churn percentage:"""

df["Churn Count"] = df["Customer Status"].apply(lambda x: 1 if x == "Stayed" else (0 if x == "Churned" else 2))
                                                ########## 1==Stayed, 2==Joined, 0==Churned

df["Churn Count"]

x=((df["Churn Count"]==0).sum()/df["Customer ID"].value_counts().sum())*100
print("Churn Percentage", x)   ## 26.53% Churn Percentage

"""## Elderly customer getting chured irrespective of gender"""

print(pd.crosstab(df["Age"], df["Customer Status"]))

df[df["Customer Status"]=="Churned"]["Age"].head(10)

df[(df["Customer Status"] == "Churned") &
   (df["Gender"] == "Male")]["Age"].sort_values(ascending=False).head(5)

df[(df["Customer Status"] == "Churned") &
   (df["Gender"] == "Female")]["Age"].sort_values(ascending=False).head(5)

df[df["Customer Status"]=="Churned"]["Age"].sort_values(ascending=False).head(5)

sns.displot(x=df["Age"],hue=df["Customer Status"], col=df["Gender"], stat="percent", bins=30,
    multiple="stack",palette="husl")


plt.show()

"""## Unamrried category shows more churn precentage comapre to married:"""

married_customers = df[df["Married"] == "Yes"]

married_churn_rate = ((married_customers["Customer Status"] == "Churned").sum()/ married_customers.shape[0]) * 100

print("Churn rate among married customers:",round(married_churn_rate, 2),"%")



print("Unmarried churn percentage:", round(((df["Married"]=="No") & (df["Customer Status"]=="Churned")).sum() / (df["Customer Status"]=="Churned").sum() * 100, 2), "%")

plt.figure(figsize=(8,5))
sns.countplot(x="Married", hue="Customer Status",data=df, stat="percent")
plt.title("Percentage Distribution of Customers by Marital Status and Status")
plt.ylabel("Percentage (%)")
plt.show()


##### countplot is only use for categorical (non numerical) data only

### Unmarried customers shows higer churn.

"""## Tenure wise churn"""

plt.figure(figsize=(10,4))
sns.histplot( x=df["Tenure in Months"], hue=df["Customer Status"], multiple="stack")
plt.title("Tenure vs Churn")
plt.show()                            ## Early tenure shows highest churn.

"""## Early tenure sengment (0-10 months) shows highest churn percentage:"""

pd.crosstab(df["Tenure in Months"], df["Customer Status"])

plt.figure(figsize=(10,4))
sns.histplot(
    data=df,
    x="Tenure in Months",
    hue="Customer Status",
    multiple="fill",
    bins=30,
    palette="husl"
)

plt.title("Customer Status Distribution Across Tenure (Per-Bin %)")
plt.ylabel("Proportion")
plt.xlabel("Tenure in Months")
plt.show()

"""## Month to month contract faces highest churn conpare to rest"""

plt.figure(figsize=(10,4))
sns.countplot(
    data=df,
    x="Contract",
    hue="Customer Status",
    stat="percent"
)
plt.title("Contract Type vs Customer Status (%)")
plt.xlabel("Contract Type")
plt.ylabel("Percentage of Customers")

plt.show()

pivot=pd.pivot_table(df, index=["Customer Status"],
                      values=["Total Long Distance Charges", "Total Charges","Monthly Charge"],
                     aggfunc="mean")
pivot


#Churned customers have the highest monthly bills, joined customers start with lower charges. Higher monthly cost is a strong churn driver.

"""## Bank Withdrawal payment method has highest churn percent:

"""

print(pd.crosstab(df["Customer Status"], df["Payment Method"]))


plt.figure(figsize=(10,4))
sns.countplot(x=df["Payment Method"],  hue=df["Customer Status"], stat="percent")
plt.show()  ##### countplot is only use for categorical (non numerical) data only

"""## Monthly Charge is higher in bank withdrawal payment method"""

df.groupby("Customer Status")[["Total Charges", "Monthly Charge", "Total Refunds"]].mean().sort_values(by="Total Charges", ascending=False)
#Montly Chrage is higher in chruned over stayed and joined categories

print(pd.crosstab(index=df["Customer Status"],
           columns=[df["Paperless Billing"], df["Phone Service"]])) ## paperlessbiling also increases the churn of customers.

print("Total Monthly Charge (Bank Withdrawal):",round(df.loc[df["Payment Method"] == "Bank Withdrawal", "Monthly Charge"].sum(), 2))

print("Total Monthly Charge (Credit Card):", round(df.loc[df["Payment Method"] == "Credit Card", "Monthly Charge"].sum(), 2))

print("Total Monthly Charge (Mailed Check):",round(df.loc[df["Payment Method"] == "Mailed Check", "Monthly Charge"].sum(), 2))



plt.figure(figsize=(10,4))
sns.barplot(x=df["Payment Method"], y=df["Monthly Charge"], hue=df["Customer Status"])
plt.show()

"""## Bank withdrawl and Mailed check has higer churn compare to credit card"""

x = pd.crosstab(df["Payment Method"], df["Customer Status"], normalize="index")*100
x

# Create crosstab of counts, normalized by Payment Method

payment_churn_crosstab = pd.crosstab(df["Payment Method"], df["Customer Status"], normalize="index")*100

# Convert to long format for plotting
plot_data = payment_churn_crosstab.reset_index().melt(id_vars="Payment Method", var_name="Customer Status", value_name="Percentage")

plot_data.head()

sns.barplot(
    data=plot_data,
    x="Payment Method",
    y="Percentage",
    hue="Customer Status"
)

plt.title("Customer Distribution by Payment Method (%)")
plt.ylabel("Percentage of Customers (%)")
plt.xlabel("Payment Method")
plt.xticks(rotation=45)
plt.show()                                                         ### Bank withdrawal and Mailed Check shows higher churn then creditcard.

"""## Churned customers contributes to total revenue faced high monthly charge → major loss risk"""

df.groupby(["Customer Status"])[["Total Revenue", "Total Charges", "Monthly Charge"]].mean()

df.groupby(["Customer Status","Internet Service", "Online Security", "Online Backup" ])[["Monthly Charge"]].mean()

"""### Fiber optic internet type shows highest churn"""

sns.countplot(x=df["Internet Type"], hue=df["Customer Status"], stat="percent")
plt.show()                ### Fiber optic showed higher churned.

"""## Customers with lower number of dependents shows higher churn"""

df["Dependents Group"] = pd.cut(
    df["Number of Dependents"],
    bins=[-1, 0, 2, 4, 10],
    labels=["0", "1–2", "3–4", "5+"]
)

plt.figure(figsize=(10,5))
sns.countplot(x=df["Dependents Group"], hue=df["Customer Status"], stat="percent")
plt.ylabel("Percentage of Customers")
plt.xlabel("Number of Dependents (Grouped)")
plt.title("Customer Status Distribution by Number of Dependents")
plt.show()

### less numer of dependents shows higher churn.

df.groupby(["Customer Status"])[["Avg Monthly Long Distance Charges"]].mean()

## no significan difference between customerstatus and avg monthly long distance charges.

"""## Churned customers have higher density in low-revenue range"""

sns.histplot(x=df["Total Revenue"], hue=df["Customer Status"], stat="percent", bins=30)
plt.show()

"""## Customers with high monthly charges who churn tend to do so early, before accumulating significant total charges."""

sns.histplot(x=df["Total Charges"], hue=df["Customer Status"], stat="percent", bins=30)
plt.show()

"""# 📊 Exploratory Data Analysis (EDA) Summary – Telecom Customer Churn

## 🧭 Objective
To analyze customer behavior, service usage, and account attributes to identify the key factors driving **customer churn**.

---

## ⚙️ Dataset Overview
- **Total Customers:** 7,043  
- **Target Variable:** `Customer Status` → {Stayed, Churned, Joined}  
- **Feature Categories:**
  - Demographics: Gender, Age, Marital Status, Dependents  
  - Account Info: Tenure, Contract Type, Payment Method, Paperless Billing  
  - Services: Internet, Phone, Streaming, Security, Backup  
  - Financial: Monthly Charges, Total Charges, Total Revenue  

✅ **Data Quality:** no major missing values, categorical variables encoded, numeric features standardized, outliers handled selectively.

---

## 👥 Customer Demographics Insights
| Feature | Observation | Insight |
|----------|--------------|----------|
| Gender | Nearly balanced | Minimal impact on churn |
| Marital Status | ~48% Married, ~52% Unmarried | Unmarried churn slightly more |
| Dependents | Customers without dependents churn more | Indicates less stability |

---

## 📆 Tenure and Loyalty
- **Average Tenure:** ~30 months  
- **Churn Rate:** sharply higher for customers with tenure < 12 months  
- **Long-term customers (≥36 months)** show very low churn.

**Business Insight:**  
The **first year of service** is the critical churn window; focus retention on new customers within 6–12 months.

---

## 💸 Billing and Payment Insights
| Factor | Pattern | Implication |
|---------|----------|-------------|
| Monthly Charges | Higher charges → higher churn | Review high-charge plans |
| Contract Type | Month-to-month churns most | Incentivize 1- or 2-year contracts |
| Payment Method | Bank Withdrawal churns most | Billing experience issues |
| Paperless Billing | More churn | Possibly price-sensitive users |

---

## 🌐 Service Usage Insights
| Service | Pattern | Insight |
|----------|----------|----------|
| Internet | Fiber-optic users churn more | Pricing or reliability issues |
| Security/Backup | Absence correlates with churn | Bundles improve stickiness |
| Streaming | Mixed effect | Weak retention driver |

---

## 💰 Revenue Analysis
- **Avg Churned Monthly Charge:** ~\$73.34  
- **Churned customers** contribute higher revenue → major loss risk.

**Business Takeaway:**  
High-value customers leaving; target loyalty programs or discounts.

---

## 📞 Contract and Service Type
| Contract Type | Churn % | Retention Tip |
|----------------|----------|----------------|
| Month-to-Month | ~45% | Add loyalty benefits |
| One-Year | ~11% | Offer renewal rewards |
| Two-Year | ~3% | Very stable |


---

## 🚦 Churn Distribution
| Status | Count | % |
|---------|--------|--|
| Stayed | 4,720 | 67% |
| Churned | 1,869 | 26% |
| Joined | 454 | 6% |

*Class imbalance addressed using SMOTE.*

---

## 🧩 Key Takeaways
- Churn is primarily behavioral and pricing-driven.  
- Early-tenure, month-to-month, high-bill customers are at highest risk.  
- Retaining even 10% of high-value churners yields major revenue gains.

**Retention levers:**
- Encourage longer contracts  
- Discounts for high spenders  
- Engage early-tenure customers  
- Bundle value-added services

---

## 🏁 Summary
> Churn is mainly driven by **short tenure, flexible contracts, and higher billing amounts** — targeting these customers early can significantly reduce churn.

## Machine Learning model establishment
"""

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from imblearn.over_sampling import BorderlineSMOTE
import pandas as pd


df=pd.read_excel("teleco_churn_clean_data.xlsx")

# Save Customer ID BEFORE modifying anything
customer_ids = df["Customer ID"].values


# Create Geo-Clusters from Latitude & Longitude

kmeans = KMeans(n_clusters=6, random_state=42)
df["GeoCluster"] = kmeans.fit_predict(df[["Latitude", "Longitude"]])



# Define features X and target y. Do NOT modify df itself.

y = df["Customer Status"]   # target

X = df.drop([
    "Customer ID",         # only removed from features,
    "Customer Status",     # but still exists in df
    "City",
    "Zip Code",
    "Latitude",
    "Longitude"
], axis=1)



# One-Hot Encoding

X = pd.get_dummies(X, drop_first=True)



# Label Encoding for target

encoders = {}
label = LabelEncoder()
y = label.fit_transform(y.astype(str))
encoders["Customer Status"] = label



# Train-Test Split

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=0
)


#Scaling

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)



# Handle imbalance using Borderline SMOTE

sm = BorderlineSMOTE(kind='borderline-1', random_state=0)
x_train_resample, y_train_resample = sm.fit_resample(x_train_scaled, y_train)


# Check balance

print("Before SMOTE:\n", pd.Series(y_train).value_counts())
print("\nAfter Borderline SMOTE:\n", pd.Series(y_train_resample).value_counts())

print("\nEncoded Target (y):")
print(y)

print("\nEncoded Feature DataFrame (X):")
display(X.head())

"""## Label encoders decoding  """

label_encoder = encoders["Customer Status"]

print("Churned =", label_encoder.transform(["Churned"])[0])
print("Joined  =", label_encoder.transform(["Joined"])[0])
print("Stayed  =", label_encoder.transform(["Stayed"])[0])

"""## Model selection and evaluation"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import *

from xgboost import XGBClassifier
from catboost import CatBoostClassifier



models = { "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced",random_state=0),

    "Decision Tree": DecisionTreeClassifier(max_depth=6,class_weight="balanced",random_state=0),

    "Random Forest": RandomForestClassifier(n_estimators=200,max_depth=6,class_weight="balanced",random_state=0),

    "Gradient Boosting": GradientBoostingClassifier(n_estimators=200,max_depth=3,random_state=0),

    "Naive Bayes": GaussianNB(),

    "SVM (RBF)": SVC(probability=True,class_weight="balanced",random_state=0),

    "XGBoost": XGBClassifier(n_estimators=200,max_depth=6,eval_metric="mlogloss",random_state=0,use_label_encoder=False),

    "CatBoost": CatBoostClassifier(iterations=200, max_depth=6, loss_function="MultiClass", random_state=0, verbose=False)}




results = []

for name, model in models.items():
    print("\n======================================")
    print(f"MODEL: {name}")
    print("======================================")

    ### Train model
    model.fit(x_train_resample, y_train_resample)

    ### LOSS FUNCTION (TRAIN & TEST)
    y_train_probabilities = model.predict_proba(x_train_resample)
    y_test_probabilities = model.predict_proba(x_test_scaled)

    train_log_loss = log_loss(y_train_resample, y_train_probabilities)
    test_log_loss = log_loss(y_test, y_test_probabilities)

    print(f"Train Log Loss: {train_log_loss:.4f}")
    print(f"Test  Log Loss: {test_log_loss:.4f}")





    ### PREDICTIONS
    y_train_predictions = model.predict(x_train_resample)
    y_test_predictions = model.predict(x_test_scaled)




    ### ACCURACY (TRAIN & TEST)
    train_accuracy = accuracy_score(y_train_resample, y_train_predictions)
    test_accuracy = accuracy_score(y_test, y_test_predictions)

    print(f"Train Accuracy: {train_accuracy:.4f}")
    print(f"Test  Accuracy: {test_accuracy:.4f}")

    ### CLASSIFICATION METRICS (TEST)
    precision = precision_score(y_test, y_test_predictions, average="weighted", zero_division=0)
    recall = recall_score(y_test, y_test_predictions, average="weighted", zero_division=0)
    f1 = f1_score(y_test, y_test_predictions, average="weighted", zero_division=0)

    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1-score : {f1:.4f}")

    ### ROC-AUC (MULTICLASS)
    roc_auc = roc_auc_score(y_test, y_test_probabilities, multi_class="ovr", average="weighted")
    print(f"ROC-AUC Score: {roc_auc:.4f}")

    ### CONFUSION MATRIX
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_test_predictions))

    print("\nClassification Report:")
    print(classification_report(y_test, y_test_predictions, zero_division=0))

    ### SAVE RESULTS
    results.append({
        "Model": name,
        "Train Log Loss": train_log_loss,
        "Test Log Loss": test_log_loss,
        "Train Accuracy": train_accuracy,
        "Test Accuracy": test_accuracy,
        "F1-score": f1,
        "ROC-AUC": roc_auc
    })

df_model_data=pd.DataFrame(results)
df_model_data

"""Multiple models were evaluated using train–test log loss, accuracy, ROC-AUC, and confusion matrices to assess both performance and generalization. Models showing underfitting or severe overfitting were excluded. Random Forest was selected as it achieved a strong test ROC-AUC with minimal train–test performance gap, indicating stable generalization. Its robustness and resistance to overfitting make it suitable for real-world deployment.

### Pretuned RandomForest
"""

# Pretuned RandomForest
RandomForest_model = models["Random Forest"]
RandomForest_model.fit(x_train_resample, y_train_resample)
print("Train accuracy:", RandomForest_model.score(x_train_resample, y_train_resample))
print("Test accuracy:", RandomForest_model.score(x_test_scaled, y_test))

"""### Fine tuned random forest"""

RandomForest_tuned = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=0
)


RandomForest_tuned.fit(x_train_resample, y_train_resample)

# Predictions (Train & Test)
y_train_pred = RandomForest_tuned.predict(x_train_resample)
y_train_prob = RandomForest_tuned.predict_proba(x_train_resample)

y_test_pred = RandomForest_tuned.predict(x_test_scaled)
y_test_prob = RandomForest_tuned.predict_proba(x_test_scaled)

# Log Loss
train_log_loss = log_loss(y_train_resample, y_train_prob)
test_log_loss = log_loss(y_test, y_test_prob)

# Metrics (Test)
accuracy = accuracy_score(y_test, y_test_pred)
precision = precision_score(y_test, y_test_pred, average="weighted", zero_division=0)
recall = recall_score(y_test, y_test_pred, average="weighted", zero_division=0)
f1 = f1_score(y_test, y_test_pred, average="weighted", zero_division=0)
roc_auc = roc_auc_score(y_test, y_test_prob, multi_class="ovr")

# Results
print(f"Train Log Loss: {train_log_loss:.4f}")
print(f"Test  Log Loss: {test_log_loss:.4f}")

print(f"Train Accuracy: {accuracy_score(y_train_resample, y_train_pred):.4f}")
print(f"Test  Accuracy: {accuracy_score(y_test, y_test_pred):.4f}")

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision (weighted): {precision:.4f}")
print(f"Recall (weighted): {recall:.4f}")
print(f"F1-score (weighted): {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

print("\nClassification Report:\n", classification_report(y_test, y_test_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))

"""After fine-tuning, training log loss dropped from ~0.41 to 0.21, while test log loss reduced more modestly from ~0.48 to 0.38, increasing the train–test gap. This indicates higher model capacity and controlled variance, not an error, and is expected as the model becomes more expressive.


Train loss should always be lower than test loss; a small to moderate gap is normal and expected because the model has seen training data.
If both train and test loss are high, the model is underfitting and needs more capacity or better features.

If train loss is very low but test loss is much higher (≥2×), the model is overfitting and learning noise.

Accuracy gap should be interpreted with test accuracy: a higher gap is acceptable if test accuracy improves.

Acceptable accuracy gap is ~3–8% (good) and ~8–15% (controlled overfitting); beyond 15–20% indicates severe overfitting.

Tuning often increases the gap because training improves faster than testing; this is normal as long as test loss decreases or stays stable.

Stop tuning when test metrics stop improving, not when the gap becomes zero—zero gap usually indicates underfitting.

### Optimal Attrition Probability Threshold
"""

# Convert target to binary (Churned = 1, others = 0)
y_test_binary = (y_test == 0).astype(int)

# Get churn probabilities (column 0 = class 'Churned')
churn_probs = RandomForest_tuned.predict_proba(x_test_scaled)[:, 0]

#Compute ROC curve
fpr, tpr, thresholds = roc_curve(y_test_binary, churn_probs)

#Find best threshold (Youden’s J index)
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]

print(f"Optimal Churn Threshold: {optimal_threshold:.3f}")

# Plot ROC Curve
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label='ROC Curve')
plt.plot([0,1], [0,1], linestyle='--', color='gray')
plt.scatter(fpr[optimal_idx], tpr[optimal_idx], color='red', label=f'Optimal Threshold = {optimal_threshold:.2f}')
plt.title("ROC Curve — Churn Model")
plt.xlabel("False Positive Rate (1 - Specificity)")
plt.ylabel("True Positive Rate (Sensitivity)")
plt.legend()
plt.show()

# Scale full dataset
X_full_scaled = scaler.transform(X)

# Predict class and probabilities
predicted_class = RandomForest_tuned.predict(X_full_scaled)
predicted_probabilities = RandomForest_tuned.predict_proba(X_full_scaled)

# Decode numeric predictions into labels
predicted_labels = encoders["Customer Status"].inverse_transform(predicted_class)

# Get the churn probability column
churn_index = list(encoders["Customer Status"].classes_).index("Churned")
churn_probability = predicted_probabilities[:, churn_index]

# Build final prediction dataframe
df_predictions = pd.DataFrame({
    "Customer ID": customer_ids,
    "Actual Status": encoders["Customer Status"].inverse_transform(y),
    "Predicted Status": predicted_labels,
    "Churn Probability": churn_probability
})

# Adjusted prediction (only marks 'Churned' if probability is high)
df_predictions["Adjusted Prediction"] = np.where(
    churn_probability >= optimal_threshold,
    "Churned",
    df_predictions["Predicted Status"]
)

# Show output
df_predictions.head(10)

# Sort customers by churn probability (descending)
results_sorted = df_predictions.sort_values(
    by="Churn Probability", ascending=False
).head(10)

print("Top 10 High-Risk Customers:")
results_sorted

"""### Feature importances (top 10)"""

# Feature Importance Plot ---

importances = pd.Series(RandomForest_tuned.feature_importances_, index=X.columns)
top10 = importances.sort_values(ascending=False).head(10).reset_index()
top10.columns = ["Feature", "Importance"]

plt.figure(figsize=(10,6))
sns.barplot(
    data=top10,
    y="Feature",
    x="Importance",
    palette="viridis",
    edgecolor="black"
)
plt.title("Top 10 Most Important Features Influencing Customer Status", fontsize=14, fontweight="bold", pad=15)
plt.xlabel("Feature Importance Score", fontsize=12)
plt.ylabel("")
plt.grid(axis="x", linestyle="--", alpha=0.4)
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""###  Churn Probability Distribution Plot (Using the found optimal threshold)"""

df_predictions["Churn Probability"] = churn_probability
threshold = optimal_threshold # Use the calculated threshold

plt.figure(figsize=(8,5))
sns.kdeplot(data=df_predictions, x="Churn Probability", hue="Actual Status", fill=True, alpha=0.4)
plt.axvline(threshold, color='red', linestyle='--', linewidth=2, label=f"Optimal Threshold = {threshold:.3f}")
plt.title("Churn Probability Distribution by Actual Status", fontsize=12, fontweight='bold')
plt.xlabel("Predicted Churn Probability")
plt.ylabel("Density")
plt.legend()
plt.show()

"""### Define risk categories based on probability thresholds"""

def risk_segment(p):
    if p >= threshold:
        return "High Risk"
    elif p >= 0.15:
        return "Medium Risk"
    else:
        return "Low Risk"

df_predictions["Risk Segment"] = df_predictions["Churn Probability"].apply(risk_segment)


df_predictions.head()

total_customers = len(df_predictions)
high_risk_count = (df_predictions["Risk Segment"] == "High Risk").sum()

high_risk_percentage = (high_risk_count / total_customers) * 100

print("Total Customers:", total_customers)
print("High-Risk Customers:", high_risk_count)
print("High-Risk Percentage: {:.2f}%".format(high_risk_percentage))

"""### Risk summary"""

risk_summary = df_predictions["Risk Segment"].value_counts().reset_index()
risk_summary.columns = ["Risk Segment", "Count"]
risk_summary["Percentage"] = (risk_summary["Count"] / total_customers) * 100

risk_summary

"""### Unknown Customers for Prediction"""

import pandas as pd


new_customers = pd.DataFrame([
    {
        "Customer ID": "CUST-10001",
        "Gender": "Female",
        "Age": 28,
        "Married": "No",
        "Dependents": "No",
        "Tenure in Months": 6,
        "Contract": "Month-to-Month",
        "Payment Method": "Bank Withdrawal",
        "Paperless Billing": "Yes",
        "Internet Type": "Fiber Optic",
        "Online Security": "No",
        "Online Backup": "No",
        "Device Protection": "No",
        "Tech Support": "No",
        "Streaming TV": "Yes",
        "Streaming Movies": "Yes",
        "Multiple Lines": "No",
        "Monthly Charge": 95.50,
        "Total Charges": 573.0,
        "Total Revenue": 573.0
    },
    {
        "Customer ID": "CUST-10002",
        "Gender": "Male",
        "Age": 45,
        "Married": "Yes",
        "Dependents": "Yes",
        "Tenure in Months": 36,
        "Contract": "One Year",
        "Payment Method": "Credit Card",
        "Paperless Billing": "No",
        "Internet Type": "DSL",
        "Online Security": "Yes",
        "Online Backup": "Yes",
        "Device Protection": "Yes",
        "Tech Support": "Yes",
        "Streaming TV": "Yes",
        "Streaming Movies": "No",
        "Multiple Lines": "Yes",
        "Monthly Charge": 65.20,
        "Total Charges": 2347.2,
        "Total Revenue": 2347.2
    },
    {
        "Customer ID": "CUST-10003",
        "Gender": "Female",
        "Age": 33,
        "Married": "No",
        "Dependents": "No",
        "Tenure in Months": 12,
        "Contract": "Month-to-Month",
        "Payment Method": "Electronic Check",
        "Paperless Billing": "Yes",
        "Internet Type": "Fiber Optic",
        "Online Security": "No",
        "Online Backup": "No",
        "Device Protection": "No",
        "Tech Support": "No",
        "Streaming TV": "No",
        "Streaming Movies": "Yes",
        "Multiple Lines": "No",
        "Monthly Charge": 89.45,
        "Total Charges": 1073.4,
        "Total Revenue": 1073.4
    },
    {
        "Customer ID": "CUST-10004",
        "Gender": "Male",
        "Age": 60,
        "Married": "Yes",
        "Dependents": "Yes",
        "Tenure in Months": 72,
        "Contract": "Two Year",
        "Payment Method": "Mailed Check",
        "Paperless Billing": "No",
        "Internet Type": "DSL",
        "Online Security": "Yes",
        "Online Backup": "Yes",
        "Device Protection": "Yes",
        "Tech Support": "Yes",
        "Streaming TV": "Yes",
        "Streaming Movies": "Yes",
        "Multiple Lines": "Yes",
        "Monthly Charge": 59.90,
        "Total Charges": 4312.8,
        "Total Revenue": 4312.8
    }
])

display(new_customers)

"""## New data processing for the model"""

# 1. Copy the new data
X_new = new_customers.copy()

# 2. Drop the same columns removed during training
X_new = X_new.drop(["Customer ID", "City", "Zip Code", "Latitude", "Longitude"], axis=1, errors="ignore")

# 3. One-hot encode
X_new = pd.get_dummies(X_new, drop_first=True)

# 4. Match training columns (fill missing with 0)
X_new = X_new.reindex(columns=X.columns, fill_value=0)

# 5. Scale
X_new_scaled = scaler.transform(X_new)

# 6. Predict class + probabilities
# Predict class labels (numeric)
predicted_class_numbers = RandomForest_tuned.predict(X_new_scaled)

# Predict class probabilities
predicted_probs = RandomForest_tuned.predict_proba(X_new_scaled)

# Convert numeric predictions back to actual class names (Stayed / Churned / Joined)
predicted_class_labels = encoders["Customer Status"].inverse_transform(predicted_class_numbers)


results = new_customers.copy()
results["Predicted_Status"] = predicted_class_labels


# Since we know the order of classes:
# ['Churned', 'Joined', 'Stayed']

results["P(Churned)"] = predicted_probs[:, 0]
results["P(Joined)"]  = predicted_probs[:, 1]
results["P(Stayed)"]  = predicted_probs[:, 2]

results["Risk Segment"] = results["P(Churned)"].apply(risk_segment)

display(results[["Customer ID", "Predicted_Status", "P(Churned)", "P(Joined)", "P(Stayed)", "Risk Segment"]])

"""## 🤖 Machine Learning Summary Steps  

## 🧠 Overview  
Customer churn is one of the biggest profitability challenges in telecom. This project applies a **Random Forest Classifier** to predict which customers are most likely to **churn (attrite)**, combining **Python (scikit-learn)** for modeling and **Power BI** for business intelligence dashboards.

---

## ⚙️  Data Preprocessing

| Step | Description |
|------|--------------|
| **1.1 Data Cleaning** | Removed irrelevant columns (`Churn Reason`, `Churn Category`). |
| **1.2 Missing Values** | Replaced missing categorical values with the **mode** and numerical values with the **median**. |
| **1.3 Feature Encoding** | Used `pd.get_dummies()` for categorical variables. |
| **1.4 Target Encoding** | Applied `LabelEncoder` to `Customer Status` → {Stayed, Churned, Joined} → {0, 1, 2}. |
| **1.5 Train-Test Split** | 80% training / 20% testing with `stratify=y` for balanced classes. |
| **1.6 Feature Scaling** | Standardized numeric columns with `StandardScaler`. |
| **1.7 Imbalance Handling** | Balanced target classes using **SMOTE** (Synthetic Minority Oversampling Technique). |

---

## 🧩  Model Training

| Model | Key Parameters | Purpose |
|--------|----------------|----------|
| **Random Forest (baseline)** | `class_weight='balanced', random_state=0` | Handles imbalance & non-linearity |
| **Logistic Regression** | `max_iter=1000, random_state=0` | Linear benchmark |
| **Decision Tree** | `random_state=0` | Interpretable baseline |
| **Naive Bayes** | Default params | Probabilistic baseline |

All models were trained on **resampled + scaled** data (`x_train_resample`, `y_train_resample`).

---

##  📊 Model Performance (Final Results)


```python
RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=0
)
```


**Performance:**
- Train Accuracy: 0.94
- Test Accuracy: 0.83
- ROC-AUC: 0.93
- Precision: 0.83
- Recall: 0.82
- F1 Score: 0.82
- ROC AUC: 0.93


✅ **Interpretation**  
- Fine-tuning improved **generalization** and reduced overfitting.  
- **AUC = 0.936** shows strong discrimination across classes (*Stayed / Churned / Joined*).  
- Balanced metrics confirm deployment-ready stability.


---

## 📈 Model Insights

### 🔹 Key Churn Drivers

- Tenure, billing type, and contract length drive churn risk.
- Fiber-optic internet & paperless billing → higher churn probability.
- Auto-pay + long-term contracts → better retention.

### 🔹 Top 10 Feature Importances

1️⃣ Tenure in Months
2️⃣ Total Revenue
3️⃣ Total Charges
4️⃣ Total Long Distance Charges
5️⃣ Contract_Two Year
6️⃣ Number of Referrals
7️⃣ Monthly Charge
8️⃣ Age
9️⃣ Paperless Billing_Yes
🔟 Payment Method_Credit Card

---

## 📉  ROC Curve, Probability Distribution & Thresholds

| Parameter | Value |
|-----------|-------|
| Optimal Churn Probability Threshold | 0.30 |
| ROC-AUC Score | 0.93 |

### 🧭 Interpretation
- Customers with Churn Probability ≥ 0.3 are high-risk attriters.
- The 0.32 threshold balances sensitivity (True Positive Rate) and specificity (1 – False Positive Rate).
- ROC curve and probability distribution visuals confirm robust separation between churned and non-churned customers.

---

## 🏁  Business Application

### 🎯 Deployment Strategy
- Retrain and deploy monthly to detect emerging churn patterns.
- Integrate predictions into Power BI dashboards for real-time business decisions.

### Customer Segmentation

| Probability Range | Segment | Action |
|-------------------|---------|--------|
| P(Churned) ≥ 0.30 | High-Risk | Retention offers & personalized discounts |
| 0.30 ≤ P(Churned) < 0.30 | Medium-Risk | Customer support & plan improvements |
| < 0.30 | Safe | Regular loyalty programs & engagement |

---

##  Technical Stack
- **Python** (scikit-learn, pandas, numpy)
- **SMOTE** for imbalance handling
- **Random Forest Classifier** (primary model)
- **Power BI** for dashboards
- **StandardScaler** for feature scaling
- **LabelEncoder** for target encoding

---

## 📌 Project Status
✅ **Production-Ready** — Model demonstrates balanced performance with strong generalization capabilities and is ready for deployment in real-world telecom churn prediction scenarios.
"""

