# -*- coding: utf-8 -*-
"""Teleco Chustomer Churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIzK6ghsArX9h5p39BbGeqw_KxYu5JOE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("telecom_customer_churn.csv")
df.head()
df.columns = df.columns.str.strip()
df.drop(columns=["Churn Category", "Churn Reason",], axis=1, inplace=True) ### Unnecessary columns with NaN values thus removed from the data.
df.head(2)

df.info()

df.shape

df.head()
df.isnull().sum().sum()  ## total NaN values in the data =np.int64(20501)

df["Customer ID"].duplicated().sum() ## no duplicates

"""## NaN removing"""

for column in df.select_dtypes(object).columns:
  df[column]=df[column].fillna(df[column].mode()[0])

df.isnull().sum()

for column in df.select_dtypes("number").columns:
  df[column]=df[column].fillna(df[column].median())

df.isnull().sum().sum()
df.head(2)

"""## Outlier cliping"""

for column in df.select_dtypes(include="number").columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    # Cap values within limits
    df[column] = df[column].clip(lower_limit, upper_limit)

sns.boxplot(x=df["Monthly Charge"])
plt.show()

# Save cleaned dataset properly as Excel file
df.to_excel("teleco_churn_clean_data.xlsx", index=False)

# Verify file saved successfully
import os
print(os.listdir('/content'))    ### for power bi analysis

"""## Total churn percentage:"""

##
df["Customer ID"].value_counts().sum() ## total customers=7043

print((df["Customer Status"]=="Stayed").sum())  ## total customer stayed 4720

print((df["Customer Status"]=="Joined").sum())  ## total customer 454 joined

print((df["Customer Status"]=="Churned").sum()) ## ## total customer churned =1869

print(((df["Customer Status"]=="Stayed").sum()/df["Customer ID"].value_counts().sum())*100) #67% Customer stayed

print(((df["Customer Status"]=="Churned").sum()/df["Customer ID"].value_counts().sum())*100)  #26.53% Customer got churned

df["Churn Count"] = df["Customer Status"].apply(lambda x: 1 if x == "Stayed" else (0 if x == "Churned" else 2))
                                                ########## 1==Stayed, 2==Joined, 0==Churned

df["Churn Count"]

x=((df["Churn Count"]==0).sum()/df["Customer ID"].value_counts().sum())*100
print("Churn Percentage", x)   ## 26.53% Churn Percentage

"""## Elderly customer getting chured irrespective of gender"""

print(pd.crosstab(df["Age"], df["Customer Status"]))

df[df["Customer Status"]=="Churned"]["Age"].head(10)

df[(df["Customer Status"] == "Churned") &
   (df["Gender"] == "Male")]["Age"].sort_values(ascending=False).head(5)

df[(df["Customer Status"] == "Churned") &
   (df["Gender"] == "Female")]["Age"].sort_values(ascending=False).head(5)

df[df["Customer Status"]=="Churned"]["Age"].sort_values(ascending=False).head(5)

sns.displot(x=df["Age"],hue=df["Customer Status"], col=df["Gender"], stat="percent", bins=30,
    multiple="stack",palette="husl")


plt.show()

"""## Unamrried category shows more churn precentage comapre to married:"""

print(((df["Married"]=="Yes").sum()/df["Customer ID"].value_counts().sum())*100)  ## married 48.3%
print(((df["Married"]=="No").sum()/df["Customer ID"].value_counts().sum())*100)   ## unmarried 51.9%

plt.figure(figsize=(8,5))
sns.countplot(x="Married", hue="Customer Status",data=df, stat="percent")
plt.title("Churn Rate by Marital Status (Normalized %)")
plt.ylabel("Percentage (%)")
plt.show()


##### countplot is only use for categorical (non numerical) data only

### Unmarried customers shows higer churn.

"""## Tenure wise churn"""

plt.figure(figsize=(10,4))
sns.histplot( x=df["Tenure in Months"], hue=df["Customer Status"], multiple="stack")
plt.title("Tenure vs Churn")
plt.show()                            ## Early tenure shows highest churn.

"""## Early tenure sengment (0-10 months) shows highest churn percentage:"""

pd.crosstab(df["Tenure in Months"], df["Customer Status"])

plt.figure(figsize=(10,4))
sns.histplot(
    x=df["Tenure in Months"],
    hue=df["Customer Status"],
    multiple="fill",      # each bin sums to 100%
    stat="percent",       # plot percentages
    bins=30,
    common_norm=False,
    palette="husl"  # normalize each hue group independently
)

plt.title("Normalized Tenure vs Churn (%)")
plt.ylabel("Percentage (%)")
plt.show()

"""## Month to month contract faces highest churn conpare to rest"""

plt.figure(figsize=(10,4))
sns.countplot(
    data=df,
    x="Contract",
    hue="Customer Status",
    stat="percent"
)
plt.title("Contract Type vs Customer Status (%)")
plt.xlabel("Contract Type")
plt.ylabel("Percentage of Customers")

plt.show()

pivot=pd.pivot_table(df, index=["Customer Status"],
                      values=["Total Long Distance Charges", "Total Charges","Monthly Charge"],
                     aggfunc="mean")
pivot

"""## Bank Withdrawal payment method has highest churn percent:

"""

print(pd.crosstab(df["Customer Status"], df["Payment Method"]))


plt.figure(figsize=(10,4))
sns.countplot(x=df["Payment Method"],  hue=df["Customer Status"], stat="percent")
plt.show()  ##### countplot is only use for categorical (non numerical) data only

"""## Monthly Charge is higher in bank withdrawal payment method"""

df.groupby("Customer Status")[["Total Charges", "Monthly Charge", "Total Refunds"]].mean().sort_values(by="Total Charges", ascending=False)
#Montly Chrage is higher in chruned over stayed and joined categories

print(pd.crosstab(index=df["Customer Status"],
           columns=[df["Paperless Billing"], df["Phone Service"]])) ## paperlessbiling also increases the churn of customers.

print(df.loc[df["Payment Method"] == "Bank Withdrawal", "Monthly Charge"].sum())  #279494.95

print(df.loc[df["Payment Method"] == "Credit Card", "Monthly Charge"].sum())      # 150445.2

print(df.loc[df["Payment Method"] == "Mailed Check", "Monthly Charge"].sum())     #17967.4


plt.figure(figsize=(10,4))
sns.barplot(x=df["Payment Method"], y=df["Monthly Charge"], hue=df["Customer Status"])
plt.show()

"""## Bank withdrawl and Mailed check has higer churn compare to credit card"""

x = pd.crosstab(df["Payment Method"], df["Customer Status"], normalize="index")*100
x

# Create crosstab of counts, normalized by Payment Method

# Convert to long format for plotting
x = x.reset_index().melt(id_vars="Payment Method", var_name="Customer Status", value_name="Percentage")

x.head()


sns.barplot(
    data=x,
    x="Payment Method",
    y="Percentage",
    hue="Customer Status"
)

plt.title("Customer Distribution by Payment Method (%)")
plt.ylabel("Percentage of Customers (%)")
plt.xlabel("Payment Method")
plt.xticks(rotation=45)
plt.show()                                                         ### Bank withdrawal and Mailed Check shows higher churn then creditcard.

"""## Churned customers contributes to total revenue faced high monthly charge → major loss risk"""

df.groupby(["Customer Status"])[["Total Revenue", "Total Charges", "Monthly Charge"]].mean()

df.groupby(["Customer Status","Internet Service", "Online Security", "Online Backup" ])[["Monthly Charge"]].mean()

"""### Fiber optic internet type shows highest churn"""

sns.countplot(x=df["Internet Type"], hue=df["Customer Status"], stat="percent")
plt.show()                ### Fiber optic showed higher churned.

"""## Customers with lower number of dependents shows higher churn"""

sns.countplot(x=df["Number of Dependents"], hue=df["Customer Status"], stat="percent")
plt.ylabel("Percentage of Customers")
plt.show()
### less numer of dependents shows higher churn.

df["Avg Monthly Long Distance Charges"].mean()
df["Monthly Charge"].mean()

"""## Churned customers have higher density in low-revenue range"""

sns.histplot(x=df["Total Revenue"], hue=df["Customer Status"], stat="percent", bins=30)
plt.show()

"""## Churned customers have higher density in low-charge range"""

sns.histplot(x=df["Total Charges"], hue=df["Customer Status"], stat="percent", bins=30)
plt.show()

"""# 📊 Exploratory Data Analysis (EDA) Summary – Telecom Customer Churn

## 🧭 Objective
To analyze customer behavior, service usage, and account attributes to identify the key factors driving **customer churn**.

---

## ⚙️ Dataset Overview
- **Total Customers:** 7,043  
- **Target Variable:** `Customer Status` → {Stayed, Churned, Joined}  
- **Feature Categories:**
  - Demographics: Gender, Age, Marital Status, Dependents  
  - Account Info: Tenure, Contract Type, Payment Method, Paperless Billing  
  - Services: Internet, Phone, Streaming, Security, Backup  
  - Financial: Monthly Charges, Total Charges, Total Revenue  

✅ **Data Quality:** no major missing values, categorical variables encoded, numeric features standardized, outliers handled selectively.

---

## 👥 Customer Demographics Insights
| Feature | Observation | Insight |
|----------|--------------|----------|
| Gender | Nearly balanced | Minimal impact on churn |
| Marital Status | ~48% Married, ~52% Unmarried | Unmarried churn slightly more |
| Dependents | Customers without dependents churn more | Indicates less stability |

---

## 📆 Tenure and Loyalty
- **Average Tenure:** ~30 months  
- **Churn Rate:** sharply higher for customers with tenure < 12 months  
- **Long-term customers (≥36 months)** show very low churn.

**Business Insight:**  
The **first year of service** is the critical churn window; focus retention on new customers within 6–12 months.

---

## 💸 Billing and Payment Insights
| Factor | Pattern | Implication |
|---------|----------|-------------|
| Monthly Charges | Higher charges → higher churn | Review high-charge plans |
| Contract Type | Month-to-month churns most | Incentivize 1- or 2-year contracts |
| Payment Method | Bank Withdrawal churns most | Billing experience issues |
| Paperless Billing | More churn | Possibly price-sensitive users |

---

## 🌐 Service Usage Insights
| Service | Pattern | Insight |
|----------|----------|----------|
| Internet | Fiber-optic users churn more | Pricing or reliability issues |
| Security/Backup | Absence correlates with churn | Bundles improve stickiness |
| Streaming | Mixed effect | Weak retention driver |

---

## 💰 Revenue Analysis
- **Avg Monthly Charge:** ~\$64  
- **Churned customers** contribute higher revenue → major loss risk.

**Business Takeaway:**  
High-value customers leaving; target loyalty programs or discounts.

---

## 📞 Contract and Service Type
| Contract Type | Churn % | Retention Tip |
|----------------|----------|----------------|
| Month-to-Month | ~45% | Add loyalty benefits |
| One-Year | ~11% | Offer renewal rewards |
| Two-Year | ~3% | Very stable |


---

## 🚦 Churn Distribution
| Status | Count | % |
|---------|--------|--|
| Stayed | 4,720 | 67% |
| Churned | 1,869 | 26% |
| Joined | 454 | 6% |

*Class imbalance addressed using SMOTE.*

---

## 🧩 Key Takeaways
- Churn is primarily behavioral and pricing-driven.  
- Early-tenure, month-to-month, high-bill customers are at highest risk.  
- Retaining even 10% of high-value churners yields major revenue gains.

**Retention levers:**
- Encourage longer contracts  
- Discounts for high spenders  
- Engage early-tenure customers  
- Bundle value-added services

---

## 🏁 Summary
> Churn is mainly driven by **short tenure, flexible contracts, and higher billing amounts** — targeting these customers early can significantly reduce churn.

## Machine Learning model establishment
"""

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from imblearn.over_sampling import BorderlineSMOTE
import pandas as pd


df=pd.read_excel("teleco_churn_clean_data.xlsx")

# Save Customer ID BEFORE modifying anything
customer_ids = df["Customer ID"].values


# Create Geo-Clusters from Latitude & Longitude

kmeans = KMeans(n_clusters=6, random_state=42)
df["GeoCluster"] = kmeans.fit_predict(df[["Latitude", "Longitude"]])



# Define features X and target y. Do NOT modify df itself.

y = df["Customer Status"]   # target

X = df.drop([
    "Customer ID",         # only removed from features,
    "Customer Status",     # but still exists in df
    "City",
    "Zip Code",
    "Latitude",
    "Longitude"
], axis=1)



# One-Hot Encoding

X = pd.get_dummies(X, drop_first=True)



# Label Encoding for target

encoders = {}
label = LabelEncoder()
y = label.fit_transform(y.astype(str))
encoders["Customer Status"] = label



# Train-Test Split

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=0
)


#Scaling

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)



# Handle imbalance using Borderline SMOTE

sm = BorderlineSMOTE(kind='borderline-1', random_state=0)
x_train_resample, y_train_resample = sm.fit_resample(x_train_scaled, y_train)


# Check balance

print("Before SMOTE:\n", pd.Series(y_train).value_counts())
print("\nAfter Borderline SMOTE:\n", pd.Series(y_train_resample).value_counts())

print("\nEncoded Target (y):")
print(y)

print("\nEncoded Feature DataFrame (X):")
display(X.head())

"""## Label encoders decoding  """

label_encoder = encoders["Customer Status"]

print("Churned =", label_encoder.transform(["Churned"])[0])
print("Joined  =", label_encoder.transform(["Joined"])[0])
print("Stayed  =", label_encoder.transform(["Stayed"])[0])

"""## Model selection and evaluation"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

models = {
    "Random Forest": RandomForestClassifier(class_weight="balanced", random_state=0),
    "Logistic Regression": LogisticRegression(random_state=0, max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(class_weight="balanced", random_state=0),
    "Naive Bayes": GaussianNB(),
}

for name, model in models.items():
    print("\n=== ", name, " ===")
    model.fit(x_train_resample, y_train_resample)

    y_prediction = model.predict(x_test_scaled)

    acc = accuracy_score(y_test, y_prediction)
    precision = precision_score(y_test, y_prediction, average="weighted", zero_division=0)
    recall = recall_score(y_test, y_prediction, average="weighted")
    f1 = f1_score(y_test, y_prediction, average="weighted")
    confusion = confusion_matrix(y_test, y_prediction)
    report = classification_report(y_test, y_prediction, zero_division=0)

    print("Accuracy:", acc)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-score:", f1)
    print("\nClassification Report:\n", report)
    print("Confusion Matrix:\n", confusion)

"""### Pretuned RandomForest"""

# Pretuned RandomForest
RandomForest_model = models["Random Forest"]
RandomForest_model.fit(x_train_resample, y_train_resample)
print("Train accuracy:", RandomForest_model.score(x_train_resample, y_train_resample))
print("Test accuracy:", RandomForest_model.score(x_test_scaled, y_test))

"""### Fine tuned random forest"""

# Train tuned Random Forest
RandomForest_tuned = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=0
)

RandomForest_tuned.fit(x_train_resample, y_train_resample)

# Predictions
y_pred = RandomForest_tuned.predict(x_test_scaled)
y_prob = RandomForest_tuned.predict_proba(x_test_scaled)

# Metrics
acc = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="weighted")
recall = recall_score(y_test, y_pred, average="weighted")
f1 = f1_score(y_test, y_pred, average="weighted")
roc_auc = roc_auc_score(y_test, y_prob, multi_class="ovr")

# Results
print(f"Train Accuracy: {RandomForest_tuned.score(x_train_resample, y_train_resample):.4f}")
print(f"Test Accuracy: {RandomForest_tuned.score(x_test_scaled, y_test):.4f}")
print(f"Accuracy: {acc:.4f}")
print(f"Precision (weighted): {precision:.4f}")
print(f"Recall (weighted): {recall:.4f}")
print(f"F1-score (weighted): {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

"""### Optimal Attrition Probability Threshold

"""

# Convert target to binary (Churned = 1, others = 0)
y_test_binary = (y_test == 0).astype(int)

# Get churn probabilities (column 0 = class 'Churned')
churn_probs = RandomForest_tuned.predict_proba(x_test_scaled)[:, 0]

#Compute ROC curve
fpr, tpr, thresholds = roc_curve(y_test_binary, churn_probs)

#Find best threshold (Youden’s J index)
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]

print(f"Optimal Churn Threshold: {optimal_threshold:.3f}")

# Converted the 3-class target into a binary target for ROC analysis
# ------------------------------------------------------------------
# Our model predicts 3 classes:
#   0 = Churned
#   1 = Joined
#   2 = Stayed
#
# However, ROC curve works ONLY for binary classification.
# Therefore, we convert the 'Churned' class into 1 (positive class)
# and convert both 'Joined' and 'Stayed' into 0 (negative class).
#
# Example:
#   y_test = [0, 2, 1, 0]         → original 3-class labels
#   y_test == 0                  → [True, False, False, True]
#   (y_test == 0).astype(int)    → [1, 0, 0, 1]
#
# This produces a binary vector indicating whether each observation
# truly belongs to the churned class.
# ------------------------------------------------------------------
#y_test_binary = (y_test == 0).astype(int)


# ------------------------------------------------------------------
# Extract the predicted churn probabilities from the model
# ------------------------------------------------------------------
# predict_proba() returns probabilities for all 3 classes in order:
#   [:, 0] → P(Churned)
#   [:, 1] → P(Joined)
#   [:, 2] → P(Stayed)
#
# Since class 'Churned' is encoded as 0, we take probability column 0.
#
# Example:
#   model.predict_proba() returns:
#       [ [0.70, 0.10, 0.20],
#         [0.12, 0.80, 0.08],
#         [0.55, 0.30, 0.15] ]
#
#   Selecting [:, 0] extracts churn probabilities:
#       [0.70, 0.12, 0.55]
#
# These probabilities are used to build the ROC curve and
# determine the optimal churn threshold.
# ------------------------------------------------------------------
#churn_probs = RandomForest_tuned.predict_proba(x_test_scaled)[:, 0]

# Plot ROC Curve
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label='ROC Curve')
plt.plot([0,1], [0,1], linestyle='--', color='gray')
plt.scatter(fpr[optimal_idx], tpr[optimal_idx], color='red', label=f'Optimal Threshold = {optimal_threshold:.2f}')
plt.title("ROC Curve — Churn Model")
plt.xlabel("False Positive Rate (1 - Specificity)")
plt.ylabel("True Positive Rate (Sensitivity)")
plt.legend()
plt.show()

# Scale full dataset
X_full_scaled = scaler.transform(X)

# Predict class and probabilities
predicted_class = RandomForest_tuned.predict(X_full_scaled)
predicted_probabilities = RandomForest_tuned.predict_proba(X_full_scaled)

# Decode numeric predictions into labels
predicted_labels = encoders["Customer Status"].inverse_transform(predicted_class)

# Get the churn probability column
churn_index = list(encoders["Customer Status"].classes_).index("Churned")
churn_probability = predicted_probabilities[:, churn_index]

# Build final prediction dataframe
df_predictions = pd.DataFrame({
    "Customer ID": customer_ids,
    "Actual Status": encoders["Customer Status"].inverse_transform(y),
    "Predicted Status": predicted_labels,
    "Churn Probability": churn_probability
})

# Adjusted prediction (only marks 'Churned' if probability is high)
df_predictions["Adjusted Prediction"] = np.where(
    churn_probability >= optimal_threshold,
    "Churned",
    df_predictions["Predicted Status"]
)

# Show output
df_predictions.head(10)

# Sort customers by churn probability (descending)
results_sorted = df_predictions.sort_values(
    by="Churn Probability", ascending=False
).head(10)

print("Top 10 High-Risk Customers:")
results_sorted

"""### Feature importances (top 10)"""

# Feature Importance Plot ---

importances = pd.Series(RandomForest_tuned.feature_importances_, index=X.columns)
top10 = importances.sort_values(ascending=False).head(10).reset_index()
top10.columns = ["Feature", "Importance"]

plt.figure(figsize=(10,6))
sns.barplot(
    data=top10,
    y="Feature",
    x="Importance",
    palette="viridis",
    edgecolor="black"
)
plt.title("Top 10 Most Important Features Influencing Customer Status", fontsize=14, fontweight="bold", pad=15)
plt.xlabel("Feature Importance Score", fontsize=12)
plt.ylabel("")
plt.grid(axis="x", linestyle="--", alpha=0.4)
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

#  Churn Probability Distribution Plot (Using the found optimal threshold) ---

df_predictions["Churn Probability"] = churn_probability
threshold = optimal_threshold # Use the calculated threshold

plt.figure(figsize=(8,5))
sns.kdeplot(data=df_predictions, x="Churn Probability", hue="Actual Status", fill=True, alpha=0.4)
plt.axvline(threshold, color='red', linestyle='--', linewidth=2, label=f"Optimal Threshold = {threshold:.3f}")
plt.title("Churn Probability Distribution by Actual Status", fontsize=12, fontweight='bold')
plt.xlabel("Predicted Churn Probability")
plt.ylabel("Density")
plt.legend()
plt.show()

"""### Unknown Customers for Prediction"""

import pandas as pd


new_customers = pd.DataFrame([
    {
        "Customer ID": "CUST-10001",
        "Gender": "Female",
        "Age": 28,
        "Married": "No",
        "Dependents": "No",
        "Tenure in Months": 6,
        "Contract": "Month-to-Month",
        "Payment Method": "Bank Withdrawal",
        "Paperless Billing": "Yes",
        "Internet Type": "Fiber Optic",
        "Online Security": "No",
        "Online Backup": "No",
        "Device Protection": "No",
        "Tech Support": "No",
        "Streaming TV": "Yes",
        "Streaming Movies": "Yes",
        "Multiple Lines": "No",
        "Monthly Charge": 95.50,
        "Total Charges": 573.0,
        "Total Revenue": 573.0
    },
    {
        "Customer ID": "CUST-10002",
        "Gender": "Male",
        "Age": 45,
        "Married": "Yes",
        "Dependents": "Yes",
        "Tenure in Months": 36,
        "Contract": "One Year",
        "Payment Method": "Credit Card",
        "Paperless Billing": "No",
        "Internet Type": "DSL",
        "Online Security": "Yes",
        "Online Backup": "Yes",
        "Device Protection": "Yes",
        "Tech Support": "Yes",
        "Streaming TV": "Yes",
        "Streaming Movies": "No",
        "Multiple Lines": "Yes",
        "Monthly Charge": 65.20,
        "Total Charges": 2347.2,
        "Total Revenue": 2347.2
    },
    {
        "Customer ID": "CUST-10003",
        "Gender": "Female",
        "Age": 33,
        "Married": "No",
        "Dependents": "No",
        "Tenure in Months": 12,
        "Contract": "Month-to-Month",
        "Payment Method": "Electronic Check",
        "Paperless Billing": "Yes",
        "Internet Type": "Fiber Optic",
        "Online Security": "No",
        "Online Backup": "No",
        "Device Protection": "No",
        "Tech Support": "No",
        "Streaming TV": "No",
        "Streaming Movies": "Yes",
        "Multiple Lines": "No",
        "Monthly Charge": 89.45,
        "Total Charges": 1073.4,
        "Total Revenue": 1073.4
    },
    {
        "Customer ID": "CUST-10004",
        "Gender": "Male",
        "Age": 60,
        "Married": "Yes",
        "Dependents": "Yes",
        "Tenure in Months": 72,
        "Contract": "Two Year",
        "Payment Method": "Mailed Check",
        "Paperless Billing": "No",
        "Internet Type": "DSL",
        "Online Security": "Yes",
        "Online Backup": "Yes",
        "Device Protection": "Yes",
        "Tech Support": "Yes",
        "Streaming TV": "Yes",
        "Streaming Movies": "Yes",
        "Multiple Lines": "Yes",
        "Monthly Charge": 59.90,
        "Total Charges": 4312.8,
        "Total Revenue": 4312.8
    }
])

display(new_customers)

"""## New data processing for the model"""

# 1. Copy the new data
X_new = new_customers.copy()

# 2. Drop the same columns removed during training
X_new = X_new.drop(["Customer ID", "City", "Zip Code", "Latitude", "Longitude"], axis=1, errors="ignore")

# 3. One-hot encode
X_new = pd.get_dummies(X_new, drop_first=True)

# 4. Match training columns (fill missing with 0)
X_new = X_new.reindex(columns=X.columns, fill_value=0)

# 5. Scale
X_new_scaled = scaler.transform(X_new)

# 6. Predict class + probabilities
# Predict class labels (numeric)
predicted_class_numbers = RandomForest_tuned.predict(X_new_scaled)

# Predict class probabilities
predicted_probs = RandomForest_tuned.predict_proba(X_new_scaled)

# Convert numeric predictions back to actual class names (Stayed / Churned / Joined)
predicted_class_labels = encoders["Customer Status"].inverse_transform(predicted_class_numbers)


results = new_customers.copy()
results["Predicted_Status"] = predicted_class_labels

# Since we know the order of classes:
# ['Churned', 'Joined', 'Stayed']

results["P(Churned)"] = predicted_probs[:, 0]
results["P(Joined)"]  = predicted_probs[:, 1]
results["P(Stayed)"]  = predicted_probs[:, 2]

display(results[["Customer ID", "Predicted_Status", "P(Churned)", "P(Joined)", "P(Stayed)"]])

"""## 🤖 Machine Learning Summary Steps  

## 🧠 Overview  
Customer churn is one of the biggest profitability challenges in telecom. This project applies a **Random Forest Classifier** to predict which customers are most likely to **churn (attrite)**, combining **Python (scikit-learn)** for modeling and **Power BI** for business intelligence dashboards.

---

## ⚙️  Data Preprocessing

| Step | Description |
|------|--------------|
| **1.1 Data Cleaning** | Removed irrelevant columns (`Churn Reason`, `Churn Category`). |
| **1.2 Missing Values** | Replaced missing categorical values with the **mode** and numerical values with the **median**. |
| **1.3 Feature Encoding** | Used `pd.get_dummies()` for categorical variables. |
| **1.4 Target Encoding** | Applied `LabelEncoder` to `Customer Status` → {Stayed, Churned, Joined} → {0, 1, 2}. |
| **1.5 Train-Test Split** | 80% training / 20% testing with `stratify=y` for balanced classes. |
| **1.6 Feature Scaling** | Standardized numeric columns with `StandardScaler`. |
| **1.7 Imbalance Handling** | Balanced target classes using **SMOTE** (Synthetic Minority Oversampling Technique). |

---

## 🧩  Model Training

| Model | Key Parameters | Purpose |
|--------|----------------|----------|
| **Random Forest (baseline)** | `class_weight='balanced', random_state=0` | Handles imbalance & non-linearity |
| **Logistic Regression** | `max_iter=1000, random_state=0` | Linear benchmark |
| **Decision Tree** | `random_state=0` | Interpretable baseline |
| **Naive Bayes** | Default params | Probabilistic baseline |

All models were trained on **resampled + scaled** data (`x_train_resample`, `y_train_resample`).

---

##  📊 Model Performance (Final Results)


```python
RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=0
)
```

**Performance:**
- Train Accuracy: 0.95
- Test Accuracy: 0.83
- ROC-AUC: 0.93
- Precision: 0.83
- Recall: 0.82
- F1 Score: 0.82
- ROC AUC: 0.93


✅ **Interpretation**  
- Fine-tuning improved **generalization** and reduced overfitting.  
- **AUC = 0.936** shows strong discrimination across classes (*Stayed / Churned / Joined*).  
- Balanced metrics confirm deployment-ready stability.


---

## 📈 Model Insights

### 🔹 Key Churn Drivers

- Tenure, billing type, and contract length drive churn risk.
- Fiber-optic internet & paperless billing → higher churn probability.
- Auto-pay + long-term contracts → better retention.

### 🔹 Top 10 Feature Importances

1️⃣ Tenure in Months
2️⃣ Total Revenue
3️⃣ Total Charges
4️⃣ Total Long Distance Charges
5️⃣ Contract_Two Year
6️⃣ Number of Referrals
7️⃣ Monthly Charge
8️⃣ Age
9️⃣ Paperless Billing_Yes
🔟 Payment Method_Credit Card

---

## 📉  ROC Curve, Probability Distribution & Thresholds

| Parameter | Value |
|-----------|-------|
| Optimal Churn Probability Threshold | 0.32 |
| ROC-AUC Score | 0.93 |

### 🧭 Interpretation
- Customers with Churn Probability ≥ 0.32 are high-risk attriters.
- The 0.32 threshold balances sensitivity (True Positive Rate) and specificity (1 – False Positive Rate).
- ROC curve and probability distribution visuals confirm robust separation between churned and non-churned customers.

---

## 🏁  Business Application

### 🎯 Deployment Strategy
- Retrain and deploy monthly to detect emerging churn patterns.
- Integrate predictions into Power BI dashboards for real-time business decisions.

### Customer Segmentation

| Probability Range | Segment | Action |
|-------------------|---------|--------|
| P(Churned) ≥ 0.32 | High-Risk | Retention offers & personalized discounts |
| 0.32 ≤ P(Churned) < 0.32 | Medium-Risk | Customer support & plan improvements |
| < 0.32 | Safe | Regular loyalty programs & engagement |

---

##  Technical Stack
- **Python** (scikit-learn, pandas, numpy)
- **SMOTE** for imbalance handling
- **Random Forest Classifier** (primary model)
- **Power BI** for dashboards
- **StandardScaler** for feature scaling
- **LabelEncoder** for target encoding

---

## 📌 Project Status
✅ **Production-Ready** — Model demonstrates balanced performance with strong generalization capabilities and is ready for deployment in real-world telecom churn prediction scenarios.
"""

